-- Tapping Transaction Data Table
SELECT
    CASE
        WHEN U.CLUSTER_ID IS NULL THEN 'NULL'
        ELSE U.CLUSTER_ID
    END AS CLUSTER_ID,
    CASE
        WHEN U.GROUP_ID = 1005 THEN 'NAIROBI WATER'
        WHEN U.GROUP_ID = 1003 THEN 'UGANDA'
        ELSE NULL
    END AS LOCATION,
    U.GROUP_ID,
    U.UNIT_NAME AS DISPENSER,
    T.UNIT_ID,
    T.CARD_ID1 AS USER,
    CAST(T.LOG_RTC AS DATE) AS DATE,
    START_TIME,
    CAST(T.LOG_RTC AS TIME) AS END_TIME,
    T.VOLUME_RELEASED AS VOLUME,
    TAPPING_TIME AS DURATION,
    U.LAST_CONNECTION,
    CASE
        WHEN U.LAST_CONNECTION = '2016-01-15 12:27:48' THEN 'CONNECTED'
        WHEN U.LAST_CONNECTION < '2016-01-15 12:27:48' THEN 'NOT CONNECTED'
        ELSE NULL
    END AS CONNECTION_STATUS
FROM
    TRANS T
        JOIN
    UNIT U ON T.UNIT_ID = U.ID
WHERE
    T.VOLUME_RELEASED IS NOT NULL
        AND U.UNIT_NAME = 'MASHIMONI ONE'
        AND CAST(T.LOG_RTC AS DATE) BETWEEN '2015-04-17' AND '2015-04-18'
ORDER BY T.LOG_RTC ASC;



-- Queue Length/Idle Times Estimate Table


 SELECT U.UNIT_NAME AS DISPENSER,CAST(T.START_TIME AS DATE) AS DATE,SUM(T.VOLUME_RELEASED) AS TOTAL_VOLUME,SUM(T.QUEUE_LENGTH) AS QUEUE_LENGTH

 FROM  TRANS T
        JOIN
    UNIT U ON T.UNIT_ID = U.ID WHERE CAST(T.LOG_RTC AS DATE) BETWEEN '2015-1-01' AND '2015-12-30'
 AND T.VOLUME_RELEASED IS NOT NULL AND U.UNIT_NAME = 'MASHIMONI THREE' GROUP BY CAST(T.LOG_RTC AS DATE) ORDER BY CAST(T.LOG_RTC AS DATE) ASC;


 -- Queue Length/Idle Times Estimate (Day of week) Chart

SELECT DAYNAME('2015-1-01');

 SELECT  DAYNAME(CAST(T.START_TIME AS DATE)) AS DAY,SUM(T.QUEUE_LENGTH) AS QUEUE_LENGTH

 FROM  TRANS T
        JOIN
    UNIT U ON T.UNIT_ID = U.ID WHERE CAST(T.LOG_RTC AS DATE) BETWEEN '2015-1-01' AND '2015-12-30'
 AND T.VOLUME_RELEASED IS NOT NULL AND T.QUEUE_LENGTH IS NOT NULL AND U.UNIT_NAME = 'MASHIMONI THREE' GROUP BY DAYNAME(CAST(T.START_TIME AS DATE))
 ORDER BY CASE
    WHEN DAYNAME(CAST(T.START_TIME AS DATE)) LIKE "%MON%" THEN 1
    WHEN DAYNAME(CAST(T.START_TIME AS DATE)) LIKE "%TUES%"  THEN 2
    WHEN DAYNAME(CAST(T.START_TIME AS DATE)) LIKE "%WED%" THEN 3
    WHEN DAYNAME(CAST(T.START_TIME AS DATE)) LIKE "%THUR%"  THEN 4
    WHEN DAYNAME(CAST(T.START_TIME AS DATE)) LIKE "%FRI%" THEN 5
    WHEN DAYNAME(CAST(T.START_TIME AS DATE)) LIKE "%SAT%"  THEN 6
    ELSE 7
END;


 -- Queue Length/Idle Times Estimate (Time of Day) Chart

SELECT CASE
  WHEN CAST(T.START_TIME AS TIME) BETWEEN '03:00:00' AND '08:00:00' THEN 'EARLY MORNING'
  WHEN CAST(T.START_TIME AS TIME) BETWEEN '08:00:01' AND '11:00:00' THEN 'MID MORNING'
  WHEN CAST(T.START_TIME AS TIME) BETWEEN '11:00:01' AND '15:00:00' THEN 'AFTERNOON'
  WHEN CAST(T.START_TIME AS TIME) BETWEEN '15:00:01' AND '18:00:00' THEN  'EVENING'
  WHEN CAST(T.START_TIME AS TIME) BETWEEN '18:00:01' AND '23:00:00' THEN  'NIGHT'
  END AS TIME,

 SUM(T.QUEUE_LENGTH) AS QUEUE_LENGTH

 FROM  TRANS T
        JOIN
    UNIT U ON T.UNIT_ID = U.ID WHERE CAST(T.LOG_RTC AS DATE) BETWEEN '2015-1-01' AND '2015-12-30'
 AND T.VOLUME_RELEASED IS NOT NULL  AND T.QUEUE_LENGTH IS NOT NULL AND U.UNIT_NAME = 'MASHIMONI THREE' AND DAYNAME(CAST(T.START_TIME AS DATE)) = 'MONDAY' GROUP BY TIME ORDER BY
 CASE
 WHEN TIME LIKE "%EAR%" THEN 1
 WHEN TIME LIKE "%MID%" THEN 2
 WHEN TIME LIKE "%AFT%" THEN 3
 WHEN TIME LIKE "%EVE%" THEN 4
 WHEN TIME LIKE "%NIG%" THEN 5

END;



  -- Queue Length/Idle Times Estimate (By MONTH) Chart


 SELECT U.UNIT_NAME AS DISPENSER, MONTHNAME(CAST(T.START_TIME AS DATE)) AS MONTH,SUM(T.QUEUE_LENGTH) AS QUEUE_LENGTH

 FROM  TRANS T
        JOIN
    UNIT U ON T.UNIT_ID = U.ID WHERE CAST(T.LOG_RTC AS DATE) BETWEEN '2015-1-01' AND '2015-12-30'
 AND T.VOLUME_RELEASED IS NOT NULL AND T.QUEUE_LENGTH IS NOT NULL AND U.UNIT_NAME = 'MASHIMONI THREE' GROUP BY MONTHNAME(CAST(T.START_TIME AS DATE))
  ORDER BY CASE
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%JAN%" THEN 1
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%FEB%"  THEN 2
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%MAR%" THEN 3
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%APR%"  THEN 4
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%MAY%" THEN 5
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%JUN%"  THEN 6
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%JUL%" THEN 7
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%AUG%"  THEN 8
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%SEP%" THEN 9
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%OCT%"  THEN 10
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%NOV%" THEN 11
    ELSE 12
END;



-- Flow rate Comparative view Table

 SELECT CAST(T.START_TIME AS DATE) AS DATE,U.UNIT_NAME AS DISPENSER,AVG(T.FLOW_RATE) AS AVERAGE_FLOWRATE

 FROM
    TRANS T
        JOIN
    UNIT U ON T.UNIT_ID = U.ID
WHERE  CAST(T.LOG_RTC AS DATE) BETWEEN '2015-1-01' AND '2015-12-30'
AND T.VOLUME_RELEASED IS NOT NULL   GROUP BY CAST(LOG_RTC AS DATE) ORDER BY U.UNIT_NAME,CAST(LOG_RTC AS DATE) ASC  ;


-- Flowrate Individual View Table


 SELECT CAST(T.START_TIME AS DATE) AS DATE,U.UNIT_NAME AS DISPENSER,MAX(T.FLOW_RATE) AS MAXIMUM_FLOWRATE,MIN(T.FLOW_RATE) AS MINIMU_FLOWRATE,ROUND(AVG(T.FLOW_RATE),1) AS AVERAGE_FLOWRATE

 FROM
    TRANS T
        JOIN
    UNIT U ON T.UNIT_ID = U.ID
WHERE  CAST(T.LOG_RTC AS DATE) BETWEEN '2015-1-01' AND '2015-12-30'
AND T.VOLUME_RELEASED IS NOT NULL AND U.UNIT_NAME = 'MASHIMONI THREE' GROUP BY CAST(LOG_RTC AS DATE) ORDER BY CAST(LOG_RTC AS DATE) ASC;


-- Flow rate Individual View By Month Chart
 SELECT  MONTHNAME(CAST(T.START_TIME AS DATE)) AS MONTH,ROUND(AVG(T.FLOW_RATE),1) AS AVERAGE_FLOWRATE

 FROM
    TRANS T
        JOIN
    UNIT U ON T.UNIT_ID = U.ID
WHERE  CAST(T.LOG_RTC AS DATE) BETWEEN '2015-1-01' AND '2015-12-30'
AND T.VOLUME_RELEASED IS NOT NULL AND U.UNIT_NAME = 'MASHIMONI THREE' AND T.FLOW_RATE IS NOT NULL GROUP BY MONTHNAME(CAST(T.START_TIME AS DATE))
  ORDER BY CASE
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%JAN%" THEN 1
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%FEB%"  THEN 2
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%MAR%" THEN 3
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%APR%"  THEN 4
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%MAY%" THEN 5
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%JUN%"  THEN 6
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%JUL%" THEN 7
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%AUG%"  THEN 8
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%SEP%" THEN 9
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%OCT%"  THEN 10
    WHEN MONTHNAME(CAST(T.START_TIME AS DATE)) LIKE "%NOV%" THEN 11
    ELSE 12
END;

-- Flow rate Individual View By Time of Day Chart

SELECT CASE
  WHEN CAST(T.START_TIME AS TIME) BETWEEN '03:00:00' AND '08:00:00' THEN 'EARLY MORNING'
  WHEN CAST(T.START_TIME AS TIME) BETWEEN '08:00:01' AND '11:00:00' THEN 'MID MORNING'
  WHEN CAST(T.START_TIME AS TIME) BETWEEN '11:00:01' AND '15:00:00' THEN 'AFTERNOON'
  WHEN CAST(T.START_TIME AS TIME) BETWEEN '15:00:01' AND '18:00:00' THEN  'EVENING'
  WHEN CAST(T.START_TIME AS TIME) BETWEEN '18:00:01' AND '23:00:00' THEN  'NIGHT'
  END AS TIME,
ROUND(AVG(T.FLOW_RATE),1) AS AVERAGE_FLOWRATE

 FROM
    TRANS T
        JOIN
    UNIT U ON T.UNIT_ID = U.ID
WHERE  CAST(T.LOG_RTC AS DATE) BETWEEN '2015-1-01' AND '2015-12-30'
AND T.VOLUME_RELEASED IS NOT NULL AND  T.FLOW_RATE IS NOT NULL AND U.UNIT_NAME = 'MASHIMONI THREE'   GROUP BY TIME ORDER BY
 CASE
 WHEN TIME LIKE "%EAR%" THEN 1
 WHEN TIME LIKE "%MID%" THEN 2
 WHEN TIME LIKE "%AFT%" THEN 3
 WHEN TIME LIKE "%EVE%" THEN 4
 WHEN TIME LIKE "%NIG%" THEN 5

END;

-- Flow rate Individual View By Day of week Chart
SELECT DAYNAME(CAST(T.START_TIME AS DATE)) AS DAY,ROUND(AVG(T.FLOW_RATE),1) AS AVERAGE_FLOWRATE

 FROM
    TRANS T
        JOIN
    UNIT U ON T.UNIT_ID = U.ID
WHERE  CAST(T.LOG_RTC AS DATE) BETWEEN '2015-1-01' AND '2015-12-30'
AND T.VOLUME_RELEASED IS NOT NULL AND U.UNIT_NAME = 'MASHIMONI THREE' AND  T.FLOW_RATE IS NOT NULL GROUP BY DAYNAME(CAST(T.START_TIME AS DATE))
 ORDER BY CASE
    WHEN DAYNAME(CAST(T.START_TIME AS DATE)) LIKE "%MON%" THEN 1
    WHEN DAYNAME(CAST(T.START_TIME AS DATE)) LIKE "%TUES%"  THEN 2
    WHEN DAYNAME(CAST(T.START_TIME AS DATE)) LIKE "%WED%" THEN 3
    WHEN DAYNAME(CAST(T.START_TIME AS DATE)) LIKE "%THUR%"  THEN 4
    WHEN DAYNAME(CAST(T.START_TIME AS DATE)) LIKE "%FRI%" THEN 5
    WHEN DAYNAME(CAST(T.START_TIME AS DATE)) LIKE "%SAT%"  THEN 6
    ELSE 7
END;



-- Servicing Dispenser Date Suggestions Table
SELECT '2016-05-01' + INTERVAL a + b DAY DateSuggested
FROM
 (SELECT 0 a UNION SELECT 1 a UNION SELECT 2 UNION SELECT 3
    UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7
    UNION SELECT 8 UNION SELECT 9 ) d,
 (SELECT 0 b UNION SELECT 10 UNION SELECT 20
    UNION SELECT 30 UNION SELECT 40 UNION SELECT 50 UNION SELECT 60 UNION SELECT 70 UNION SELECT 80 UNION SELECT 90) m
WHERE '2016-05-1' + INTERVAL a + b DAY  <=  '2016-5-30' and DAYNAME('2016-05-1' + INTERVAL a + b DAY) =
(
SELECT


DAYNAME(CAST(T.START_TIME AS DATE)) AS DAY
 FROM

 TRANS T
        JOIN
    UNIT U ON T.UNIT_ID = U.ID WHERE CAST(T.LOG_RTC AS DATE) BETWEEN '2015-1-01' AND '2015-12-30'
 AND T.VOLUME_RELEASED IS NOT NULL AND T.QUEUE_LENGTH IS NOT NULL AND U.UNIT_NAME = 'MASHIMONI THREE'  GROUP BY DAYNAME(CAST(T.START_TIME AS DATE))
 ORDER BY SUM(T.QUEUE_LENGTH) LIMIT 1
)ORDER BY a + b;
