LOAD DATA LOCAL INFILE 'C:/Users/906729/Desktop/wms/Database/unit_1003_and_1005.csv' 
INTO TABLE trans  
    FIELDS TERMINATED BY ',' 
           OPTIONALLY ENCLOSED BY '"'
    LINES  TERMINATED BY '\n' -- or \r\n
(GROUP_ID, UNIT_ID,TRANSACTION_ID,LOG_RTC,CARD_TYPE,TRANSACTION_TYPE,CREDITS_AFTER,CREDITS_USED,CREDITS_TOTAL_AFTER,VOLUME_RELEASED,VOLUME_TOTAL_AFTER,CARD_ID1,CARD_ID2,NEW_WATER_PRICE);